version: "3.9"

services:
  uri-agent.api:
    image: uriteam/urisvc:uriagentprod
    container_name: uri-agent.api.prod
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--workers", "4"]
    env_file:
      - .env
    environment:
      - ENV=Production
      - URI_GATEWAY_BASE_API_URL=http://uri-gateway.api
      - PUBLIC_API_URL=https://api.urisocial.com
    restart: always
    ports:
      - "9005:80"
    networks:
      - uritest-network

networks:
  uritest-network:
    external: true
