"""
Content Calendar Service
Generates and manages 7-day data-driven content plans.

Generation pipeline (PRD Phase 1):
  1. Fetch user performance data  (PerformanceAnalyticsService)
  2. Fetch industry trend keywords (TrendDataService)
  3. Generate + score ideas        (IdeaScoringService)
  4. Select top 7 with content mix
  Falls back to pure AI generation when performance data is sparse (<5 posts).
"""

import json
import re
import uuid
import secrets
import random
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from motor.motor_asyncio import AsyncIOMotorDatabase

from app.services.AIService import AIService
from app.domain.models.chat_model import ChatModel
from app.services.TrendDataService import TrendDataService
from app.services.PerformanceAnalyticsService import PerformanceAnalyticsService
from app.services.IdeaScoringService import IdeaScoringService

# Enhanced calendar services (PRD requirements)
# NOTE: CTARecommenderService and CaptionAngleService (both static, brand/topic-blind
# lookup tables — a CTA/caption angle chosen without ever seeing the actual idea can't
# align with it) were removed 2026-08 — cta/caption_direction are now generated by the
# SAME AI call that writes the title/hook, so they're coherent with the specific idea
# by construction. See _generate_ideas below.
from app.agents.social_media_manager.services.holiday_calendar_service import HolidayCalendarService
from app.agents.social_media_manager.services.content_explainer_service import ContentExplainerService
from app.agents.social_media_manager.services.cultural_moment_service import CulturalMomentService
from app.agents.social_media_manager.services.industry_trend_service import IndustryTrendService

COLLECTION = "content_calendar_plans"


def _cal_scope(user_id: str, brand_id: Optional[str]) -> Dict[str, Any]:
    """Return a MongoDB filter that isolates calendar plans to the active brand."""
    from app.models.brand_account import BrandAccount
    personal_bid = BrandAccount.personal_brand_id(user_id)
    if brand_id and brand_id != personal_bid:
        return {"brand_id": brand_id}
    return {
        "user_id": user_id,
        "$or": [
            {"brand_id": {"$exists": False}},
            {"brand_id": None},
            {"brand_id": personal_bid},
        ],
    }

CONTENT_TYPES = ["educational", "relatable", "promotional", "behind_the_scenes", "engagement"]

# Four default mix variants — different type distributions so the shown
# percentages rotate each week rather than always reading the same numbers.
DEFAULT_MIX_VARIANTS: List[List[str]] = [
    # Variant 0 — Educational + relatable focus (edu 29%, rel 29%)
    ["educational", "relatable", "promotional", "educational", "behind_the_scenes", "relatable", "engagement"],
    # Variant 1 — Promotional + community push (pro 29%, rel 29%)
    ["promotional", "relatable", "educational", "engagement", "relatable", "promotional", "behind_the_scenes"],
    # Variant 2 — Educational-heavy week (edu 43%)
    ["educational", "promotional", "educational", "relatable", "engagement", "educational", "behind_the_scenes"],
    # Variant 3 — Community + engagement focus (rel 29%, eng 29%)
    ["relatable", "engagement", "educational", "promotional", "relatable", "behind_the_scenes", "engagement"],
]

# Keep the original as the default for backward-compat references
DEFAULT_MIX = DEFAULT_MIX_VARIANTS[0]

# Industry-specific mix overrides — also have 4 variants per industry
INDUSTRY_MIX: Dict[str, List[str]] = {
    "e-commerce": [
        "promotional", "educational", "relatable", "promotional",
        "behind_the_scenes", "engagement", "educational",
    ],
    "technology": [
        "educational", "educational", "relatable", "behind_the_scenes",
        "promotional", "engagement", "relatable",
    ],
    "food": [
        "behind_the_scenes", "promotional", "relatable", "educational",
        "engagement", "promotional", "relatable",
    ],
    "fashion": [
        "behind_the_scenes", "promotional", "relatable", "educational",
        "promotional", "engagement", "behind_the_scenes",
    ],
    "finance": [
        "educational", "educational", "engagement", "relatable",
        "educational", "promotional", "behind_the_scenes",
    ],
    "health": [
        "educational", "relatable", "engagement", "behind_the_scenes",
        "educational", "promotional", "relatable",
    ],
    "real estate": [
        "educational", "promotional", "behind_the_scenes", "relatable",
        "promotional", "engagement", "educational",
    ],
}

CONTENT_TYPE_LABELS = {
    "educational": "Educational",
    "relatable": "Relatable",
    "promotional": "Promotional",
    "behind_the_scenes": "Behind the Scenes",
    "engagement": "Engagement / Question",
}

WEEK_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

# 7 distinct hook styles — one is assigned to each day so no two posts open the same way
HOOK_STYLES = [
    "Bold statement — open with a provocative or surprising claim that stops the scroll",
    "Data/stat — lead with a specific number, percentage, or research finding",
    "Story-led — open with a short first-person or customer story (1-2 sentences max)",
    "Direct question — ask the audience something they instantly have an opinion about",
    "Myth-bust — start with a common misconception then flip it",
    "How-to opener — begin with 'Here's how…' or 'The exact steps we use to…'",
    "Relatable frustration — open with a pain point the audience recognises instantly",
]

# 7 distinct post formats — rotated across the week for visual variety
POST_FORMATS = [
    "Single image with caption",
    "Carousel (3-5 slides)",
    "Short-form video / Reel (15-30 sec concept)",
    "Text-only post (strong copy, no image needed)",
    "Poll or interactive question",
    "Infographic or data visual",
    "Before/after or side-by-side comparison",
]

# Canonical short key for each POST_FORMATS entry (index-aligned) — this is what
# actually gets stored as a day's "format" field and, downstream, what
# create_draft_from_calendar_day uses to decide HOW to generate the draft
# (e.g. routing to CarouselGenerationService). Keeping this tied to the exact
# format the AI was told to write each day's copy for is what makes the stored
# format match what the copy actually describes ("swipe through the carousel").
POST_FORMAT_TO_KEY = {
    "Single image with caption": "image",
    "Carousel (3-5 slides)": "carousel",
    "Short-form video / Reel (15-30 sec concept)": "video",
    "Text-only post (strong copy, no image needed)": "text",
    "Poll or interactive question": "poll",
    "Infographic or data visual": "infographic",
    "Before/after or side-by-side comparison": "comparison",
}


def _get_monday(ref: datetime) -> datetime:
    """Return the Monday of the week containing ref (midnight UTC)."""
    dow = ref.weekday()  # 0=Mon
    monday = ref - timedelta(days=dow)
    return monday.replace(hour=0, minute=0, second=0, microsecond=0)


def _pick_mix(industry: str, week_number: int = 0) -> List[str]:
    industry_lower = (industry or "").lower()
    for key, mix in INDUSTRY_MIX.items():
        if key in industry_lower:
            # Rotate the industry mix by week so day assignments change,
            # then swap one type slot so the ratios shift slightly
            rotation = week_number % 7
            return mix[rotation:] + mix[:rotation]
    # Use one of the 4 variants so the reported percentages change each week
    variant_idx = week_number % len(DEFAULT_MIX_VARIANTS)
    base = DEFAULT_MIX_VARIANTS[variant_idx]
    rotation = week_number % 7
    return base[rotation:] + base[:rotation]


# Topic label → content_type bucket
_TOPIC_TO_CONTENT_TYPE: Dict[str, str] = {
    "education":   "educational",
    "finance":     "educational",
    "technology":  "educational",
    "health":      "educational",
    "real estate": "educational",
    "marketing":   "educational",
    "business":    "educational",
    "motivation":  "relatable",
    "fashion":     "relatable",
    "food":        "relatable",
    "offer":       "promotional",
    "story":       "behind_the_scenes",
}


def _pick_mix_from_performance(
    performance: Dict[str, Any],
    industry: str,
    brand: Optional[Dict[str, Any]] = None,
    week_number: int = 0,
) -> List[str]:
    """
    Build a personalised 7-day content-type mix driven by this user's
    performance data.  Falls back to the industry/default mix when there
    is no historical data.
    """
    if not performance or not performance.get("has_data"):
        return _pick_mix(industry, week_number)

    avg_by_topic: Dict[str, float] = performance.get("avg_engagement_by_topic", {})
    if not avg_by_topic:
        return _pick_mix(industry, week_number)

    # Map each measured topic → content_type and accumulate weighted scores
    type_scores: Dict[str, float] = {t: 0.0 for t in CONTENT_TYPES}
    for topic, eng in avg_by_topic.items():
        ct = _TOPIC_TO_CONTENT_TYPE.get(topic.lower(), "relatable")
        type_scores[ct] = max(type_scores[ct], eng)  # take the best topic score per type

    # Boost based on brand primary_goal
    primary_goal = ((brand or {}).get("primary_goal") or "").lower()
    if "sales" in primary_goal or "revenue" in primary_goal or "convert" in primary_goal:
        type_scores["promotional"] = type_scores["promotional"] * 1.5 + 0.1
    elif "community" in primary_goal or "relationship" in primary_goal:
        type_scores["relatable"] = type_scores["relatable"] * 1.4 + 0.1
        type_scores["behind_the_scenes"] = type_scores["behind_the_scenes"] * 1.3 + 0.1
    elif "awareness" in primary_goal or "audience" in primary_goal or "grow" in primary_goal:
        type_scores["educational"] = type_scores["educational"] * 1.4 + 0.1
        type_scores["engagement"] = type_scores["engagement"] * 1.2 + 0.1

    # Always ensure every type has a non-zero floor so it can appear
    for ct in CONTENT_TYPES:
        if type_scores[ct] == 0.0:
            type_scores[ct] = 0.5

    # Distribute 7 slots proportionally to scores, minimum 1 slot per type
    total_score = sum(type_scores.values()) or 1.0
    raw_slots = {ct: max(1, round((s / total_score) * 7)) for ct, s in type_scores.items()}

    # Adjust to exactly 7 slots
    while sum(raw_slots.values()) > 7:
        # Remove a slot from the lowest-scoring over-allocated type
        excess = [(ct, raw_slots[ct]) for ct in raw_slots if raw_slots[ct] > 1]
        excess.sort(key=lambda x: type_scores[x[0]])
        raw_slots[excess[0][0]] -= 1
    while sum(raw_slots.values()) < 7:
        # Add a slot to the highest-scoring type
        best = max(type_scores, key=type_scores.get)
        raw_slots[best] += 1

    # Build ordered 7-day list: spread types across the week sensibly
    # Order: educational early week, promotional mid-week, engagement/relatable end
    day_type_order = ["educational", "relatable", "educational", "promotional",
                      "behind_the_scenes", "engagement", "relatable"]
    mix: List[str] = []
    remaining = dict(raw_slots)
    for preferred in day_type_order:
        if remaining.get(preferred, 0) > 0:
            mix.append(preferred)
            remaining[preferred] -= 1
        else:
            # Pick the type with most remaining slots
            fallback = max(remaining, key=lambda k: remaining[k])
            mix.append(fallback)
            remaining[fallback] -= 1

    print(f"[Calendar] Personalised mix from performance: {mix} (scores: {type_scores})")
    return mix


def _compute_mix_ratios(mix: List[str]) -> Dict[str, float]:
    counts: Dict[str, int] = {t: 0 for t in CONTENT_TYPES}
    for t in mix:
        counts[t] = counts.get(t, 0) + 1
    total = len(mix) or 7
    return {t: round(c / total, 2) for t, c in counts.items()}


# ── Completeness / coherence validation ────────────────────────────────────────
# Deterministic check run on every AI-generated day before it's ever shown to a
# user. A calendar entry that promises "3 things" but only gives a 2-sentence
# description, or a CTA/caption direction with no real content, is not usable —
# this catches that class of problem and drives one retry with the specific
# failures listed back to the model, rather than silently shipping an incomplete
# entry.

VIDEO_FORMATS = {
    "talking_head", "product_demo", "testimonial",
    "tutorial", "behind_the_scenes", "trend_based",
}

_NUMBER_WORDS = {
    "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10,
}


def _extract_promised_count(title: str) -> Optional[int]:
    """If a title promises a specific count ("Three things...", "5 ways...",
    "Top 4 mistakes"), return that count so key_points can be checked against
    it. None if the title doesn't make a countable claim."""
    t = title.lower()
    digit_match = re.search(r"\b(\d{1,2})\b", t)
    if digit_match:
        n = int(digit_match.group(1))
        if 2 <= n <= 10:
            return n
    for word, n in _NUMBER_WORDS.items():
        if n >= 2 and re.search(rf"\b{word}\b", t):
            return n
    return None


def _validate_day(idea: Dict[str, Any]) -> List[str]:
    """Return a list of human-readable completeness/coherence failures for one
    AI-generated day; an empty list means the day is usable as-is."""
    issues: List[str] = []
    title = str(idea.get("title") or "").strip()
    if not title:
        issues.append("title is empty")

    hook = str(idea.get("hook") or "").strip()
    if len(hook) < 10:
        issues.append("hook is missing or too short — must be an actual opening line")

    key_points = idea.get("key_points")
    if not isinstance(key_points, list) or len(key_points) < 2:
        issues.append("key_points must be a list of at least 2 concrete points")
    else:
        thin = [p for p in key_points if len(str(p).strip()) < 15]
        if thin:
            issues.append(f"{len(thin)} key_point(s) are too thin to be usable")
        promised = _extract_promised_count(title)
        if promised and len(key_points) < promised:
            issues.append(
                f"title implies {promised} points but only {len(key_points)} key_points were given"
            )

    caption_direction = str(idea.get("caption_direction") or "").strip()
    if len(caption_direction) < 15:
        issues.append("caption_direction is missing or too short")

    keywords = idea.get("keywords")
    if not isinstance(keywords, list) or len(keywords) < 1:
        issues.append("keywords must have at least 1 entry")

    if not str(idea.get("cta") or "").strip():
        issues.append("cta is empty")

    video_idea = idea.get("video_idea")
    if not isinstance(video_idea, dict):
        issues.append("video_idea is missing")
    else:
        if video_idea.get("format") not in VIDEO_FORMATS:
            issues.append(
                f"video_idea.format {video_idea.get('format')!r} is not a recognised format — "
                f"it MUST be exactly one of: {', '.join(sorted(VIDEO_FORMATS))} (no other wording, no synonyms)"
            )
        if len(str(video_idea.get("hook") or "").strip()) < 10:
            issues.append("video_idea.hook is missing or too short")
        if not video_idea.get("talking_points"):
            issues.append("video_idea.talking_points is empty")
        if not video_idea.get("scenes"):
            issues.append("video_idea.scenes is empty")
        if not str(video_idea.get("cta") or "").strip():
            issues.append("video_idea.cta is empty")

    return issues


async def _generate_ideas(
    brand: Dict[str, Any],
    mix: List[str],
    week_start: str,
    platforms: List[str],
    previous_titles: Optional[List[str]] = None,
    previous_key_points: Optional[List[str]] = None,
    trend_keywords: Optional[List[Dict[str, Any]]] = None,
    performance: Optional[Dict[str, Any]] = None,
    force: bool = False,
) -> List[Dict[str, Any]]:
    """Call AI once for all 7 day ideas. Returns list of 7 dicts."""
    brand_name = brand.get("brand_name") or "the brand"
    industry = brand.get("industry") or "business"
    voice = brand.get("brand_voice") or brand.get("derived_voice") or "professional and engaging"
    audience = brand.get("target_audience") or "general audience"
    pillars = brand.get("content_pillars") or []
    pillars_str = ", ".join(pillars) if pillars else "not specified"
    platforms_str = ", ".join(platforms) if platforms else "social media"

    # Rich brand details
    tagline = brand.get("tagline", "")
    description = brand.get("business_description") or brand.get("product_description", "")
    products = brand.get("key_products_services") or []
    products_str = ", ".join(products) if products else ""
    formats = brand.get("preferred_formats") or []
    formats_str = ", ".join(formats) if formats else ""
    cta_styles = brand.get("cta_styles") or []
    cta_str = ", ".join(cta_styles) if cta_styles else ""
    region = brand.get("region", "")
    primary_goal = brand.get("primary_goal", "")
    audience_age = brand.get("audience_age_range", "")
    key_dates = brand.get("key_dates", "")
    guardrails = brand.get("guardrails") or {}
    avoid = guardrails.get("avoid_topics") or guardrails.get("avoid") or []
    avoid_str = ", ".join(avoid) if avoid else ""
    platform_tones = brand.get("platform_tones") or {}
    voice_sample = brand.get("voice_sample", "")
    website = brand.get("website", "")
    posting_cadence = brand.get("posting_cadence", "")

    # Build platform-specific tone block if different per platform
    platform_tone_block = ""
    same_tone = brand.get("same_tone_everywhere", True)
    if not same_tone and platform_tones:
        lines = [f"  - {p}: {t}" for p, t in platform_tones.items() if t]
        if lines:
            platform_tone_block = "Platform-specific tones:\n" + "\n".join(lines)

    # Definitions for what each topic label means as post subject matter.
    # Critical: prevents AI from misreading e.g. "offer" as "promote this brand"
    # or "marketing" as "write about social media marketing for this platform".
    _TOPIC_DEFINITIONS = {
        "offer":      "deals, discounts, limited-time sales, pricing savings — e.g. a money-saving tip, a promo breakdown, a 'best deal right now' angle",
        "technology": "practical tech tools, apps, automation, AI — e.g. a tool that saves time, an automation hack, a software comparison",
        "finance":    "money management, investing, savings, budgeting, profit margins — e.g. an investment tip, a budgeting mistake, a savings strategy",
        "business":   "entrepreneurship, client acquisition, sales strategy, startup growth — e.g. how to land clients, a scaling lesson, a founder insight",
        "education":  "step-by-step guides, how-to posts, common mistakes, beginner tips — e.g. a tutorial, a 'what I wish I knew' post, a myth-bust",
        "marketing":  "audience growth tactics, brand-building, content strategy — e.g. an algorithm insight, a growth hack, a posting strategy",
        "motivation": "mindset, discipline, resilience, goal-setting — e.g. a personal growth story, a hard truth about success, an anti-procrastination angle",
        "real estate":"property investing, rental income, mortgage tips, landlord lessons",
        "fashion":    "style tips, outfit ideas, trend breakdowns, wardrobe hacks",
        "food":       "recipes, meal prep, food business tips, catering insights",
        "story":      "behind-the-scenes story, brand journey, case study, team moment",
    }

    # Resolve performance topics early — needed for both days_block and topic_override_block
    _perf_topics = (performance or {}).get("top_topics", []) if performance and performance.get("has_data") else []

    # Shuffle hook styles and formats so each week has a different assignment
    shuffled_hooks = HOOK_STYLES[:]
    shuffled_formats = POST_FORMATS[:]
    random.shuffle(shuffled_hooks)
    random.shuffle(shuffled_formats)

    if _perf_topics:
        _cycled_for_days = [_perf_topics[i % len(_perf_topics)] for i in range(7)]
        days_block = "\n".join(
            (
                f"Day {i} ({WEEK_DAYS[i]}) → "
                f"TOPIC: {_cycled_for_days[i]} (write about: {_TOPIC_DEFINITIONS.get(_cycled_for_days[i], _cycled_for_days[i])}) | "
                f"type: {mix[i]} ({CONTENT_TYPE_LABELS[mix[i]]}) | hook: {shuffled_hooks[i]} | format: {shuffled_formats[i]}"
            )
            for i in range(7)
        )
    else:
        days_block = "\n".join(
            f"Day {i} ({WEEK_DAYS[i]}) → type: {mix[i]} ({CONTENT_TYPE_LABELS[mix[i]]}) | hook: {shuffled_hooks[i]} | format: {shuffled_formats[i]}"
            for i in range(7)
        )

    avoid_repeat_block = ""
    if previous_titles:
        non_empty = [t for t in previous_titles if t.strip()]
        if non_empty:
            avoid_repeat_block = (
                "\nRecent content titles (do NOT repeat these ideas or similar angles — "
                "every idea must feel genuinely fresh and distinct from all of these):\n"
                + "\n".join(f"- {t}" for t in non_empty[:28])
            )
    if previous_key_points:
        non_empty_kp = [p for p in previous_key_points if p and p.strip()]
        if non_empty_kp:
            avoid_repeat_block += (
                "\nUnderlying points/insights already covered recently (do NOT reuse "
                "these even under a different title or phrasing — check the actual "
                "substance of your idea against this list, not just the wording):\n"
                + "\n".join(f"- {p}" for p in non_empty_kp[:40])
            )

    # ── Season / timeframe signal (req 5: consider current season) ────────────
    try:
        _week_dt = datetime.strptime(week_start, "%Y-%m-%d")
        _week_end_dt = _week_dt + timedelta(days=6)
        season_line = (
            f"Current timeframe: {_week_dt.strftime('%B %d')}–{_week_end_dt.strftime('%B %d, %Y')} "
            f"(each day below is {_week_dt.strftime('%b %d')} through {_week_end_dt.strftime('%b %d')}, in order)."
        )
    except ValueError:
        _week_dt = None
        season_line = ""

    # ── Country/holiday awareness (req 4) ──────────────────────────────────────
    country_block = ""
    if region and _week_dt is not None:
        _week_end_str = (_week_dt + timedelta(days=6)).strftime('%B %d, %Y')
        country_block = (
            f"Country/date awareness — DO THIS CHECK EXPLICITLY: this brand's audience is in "
            f"{region}. Before writing any ideas, check whether a real, well-known public "
            f"holiday, observance, or cultural date for {region} falls anywhere between "
            f"{_week_dt.strftime('%B %d')} and {_week_end_str} inclusive (not generic Western "
            f"holidays unless {region} observes them). Most weeks contain at least one minor "
            f"observance somewhere in the world — look for one that's genuinely relevant to "
            f"THIS business specifically (a bakery/gift/retail/food brand can almost always tie "
            f"into a national holiday if one falls in the window; a B2B software brand usually "
            f"can't, and that's fine). If you find one, let it shape ONE of the 7 days AND set "
            f"that day's holiday_reference field with the real date and holiday name. Never "
            f"invent a date you're not confident actually exists. If genuinely nothing relevant "
            f"falls in this exact window, leave holiday_reference null on every day."
        )

    # ── Business stage awareness (req 5) ────────────────────────────────────────
    # No dedicated "stage of growth" field exists on the brand profile today —
    # rather than block this on a new onboarding field, ask the model to infer
    # it from what's already there (description, goal, products, cadence).
    stage_block = (
        "Business stage: infer this brand's apparent stage of growth from the details "
        "above (e.g. a brand-new solo operation vs. an established team with a full "
        "product line and steady posting cadence) and let it inform tone and ideas where "
        "relevant — e.g. an early-stage brand benefits more from trust-building/story "
        "content, an established one can lean harder into authority/scale content."
    )

    # ── User-saved key dates (req 4) ────────────────────────────────────────────
    # These are dates the business owner explicitly saved in their Brand Playbook
    # (product launches, sales, anniversaries) — unlike public holidays, we have
    # the exact date already, so this is a deterministic Python match against the
    # week being generated, not something left to the model to notice on its own.
    user_date_block = ""
    if _week_dt is not None:
        _week_end_for_dates = _week_dt + timedelta(days=6)
        user_date_matches: List[tuple] = []
        for kd in (brand.get("key_dates_structured") or []):
            label = str((kd or {}).get("label") or "").strip()
            date_str = str((kd or {}).get("date") or "").strip()
            if not label or not date_str:
                continue
            try:
                kd_dt = datetime.strptime(date_str, "%Y-%m-%d")
            except ValueError:
                continue
            if _week_dt <= kd_dt <= _week_end_for_dates:
                user_date_matches.append(((kd_dt - _week_dt).days, label, date_str))
        if user_date_matches:
            lines = [
                f"  Day {di} ({WEEK_DAYS[di]}, {ds}): MUST build this day's idea around \"{lbl}\" "
                f"and set holiday_reference to {{\"name\": \"{lbl}\", \"why_relevant\": \"...\"}} on that day."
                for di, lbl, ds in user_date_matches
            ]
            user_date_block = (
                "=== MANDATORY: BUSINESS OWNER'S OWN SAVED DATES FALL IN THIS WEEK ===\n"
                "These are NOT general public holidays — the business owner personally saved these "
                "as important (product launches, sales, anniversaries). Unlike the general holiday "
                "check above, this is non-negotiable:\n"
                + "\n".join(lines)
                + "\n======================================================================="
            )

    # When force-regenerating, inject a random token so the model cannot return
    # a cached/memorised response identical to the previous generation.
    force_token_block = ""
    if force:
        token = secrets.token_hex(6)
        force_token_block = f"\n[Regeneration token: {token}] This is a fresh regeneration — produce completely different ideas from any previous plan.\n"

    # ── Market Intel block (Google Trends) ────────────────────────────────────
    market_intel_block = ""
    if trend_keywords:
        top_trends = trend_keywords[:6]
        trend_lines = []
        for kw in top_trends:
            score = kw.get("trend_score", 0)
            kw_type = kw.get("type", "trending")
            growth = kw.get("growth_rate", 0)
            suffix = f" (+{growth:.0f}% on Google)" if kw_type == "rising" and growth else f" (score: {score})"
            trend_lines.append(f"  - {kw['keyword']}{suffix}")
        intel_label = (
            "Trending keywords (use as angles/hooks within the assigned topics above — do NOT change the topic):"
            if _perf_topics else
            "Current trending topics in this industry (Market Intel — prioritise these):"
        )
        market_intel_block = intel_label + "\n" + "\n".join(trend_lines)

    # ── Performance Intelligence block ────────────────────────────────────────
    performance_block = ""
    if performance and performance.get("has_data"):
        top_topics = performance.get("top_topics", [])
        top_formats = performance.get("top_formats", [])
        best_hour = performance.get("best_posting_hour")

        perf_lines = []
        if top_topics:
            # Surface as a primary directive, not a soft hint
            perf_lines.append(
                f"PROVEN TOP TOPICS (highest engagement for this account): {', '.join(top_topics[:5])}. "
                f"AT LEAST 4 of the 7 days MUST be about one of these topics. "
                f"Blend them with the brand pillars — e.g. an Educational post should teach something from one of these top topics."
            )
        if top_formats:
            perf_lines.append(f"Best performing format: {top_formats[0]}")
        if best_hour is not None:
            perf_lines.append(f"Best posting time: {best_hour}:00")
        if perf_lines:
            performance_block = (
                "⚡ PERFORMANCE DATA — this account's real engagement history (treat as primary creative brief):\n"
                + "\n".join(f"  - {l}" for l in perf_lines)
            )

    brand_block = f"Brand: {brand_name}"
    if tagline:
        brand_block += f' — "{tagline}"'
    if industry:
        brand_block += f"\nIndustry: {industry}"
    if description:
        brand_block += f"\nWhat they do: {description}"
    if products_str:
        brand_block += f"\nKey products/services: {products_str}"
    if website:
        brand_block += f"\nWebsite: {website}"

    audience_block = f"Target audience: {audience}"
    if audience_age:
        audience_block += f" (age {audience_age})"
    if region:
        audience_block += f", {region} market"
    if primary_goal:
        audience_block += f"\nPrimary business goal: {primary_goal}"

    voice_block = f"Brand voice: {voice}"
    if voice_sample:
        voice_block += f'\nVoice example: "{voice_sample[:200]}"'
    if platform_tone_block:
        voice_block += f"\n{platform_tone_block}"
    if cta_str:
        voice_block += f"\nPreferred CTAs: {cta_str}"

    extras = []
    if formats_str:
        extras.append(f"Preferred content formats: {formats_str}")
    if key_dates:
        extras.append(f"Upcoming key dates: {key_dates}")
    if posting_cadence:
        extras.append(f"Posting cadence: {posting_cadence}")
    if avoid_str:
        extras.append(f"Topics/themes to avoid: {avoid_str}")
    extras_block = "\n".join(extras)

    # When we have engagement data, assign one proven topic to each day explicitly.
    # This leaves the AI no room to drift back to brand pillars or industry defaults.
    if _perf_topics:
        _cycled = [_perf_topics[i % len(_perf_topics)] for i in range(7)]
        _topic_lines = "\n".join(
            f"  Day {i} → TOPIC: {_cycled[i]}  ({_TOPIC_DEFINITIONS.get(_cycled[i], _cycled[i])})"
            for i in range(7)
        )
        topic_override_block = (
            f"=== MANDATORY TOPIC ASSIGNMENTS (derived from real engagement data) ===\n"
            f"Each day's post MUST be about the assigned topic — the definition in parentheses tells you exactly what the post should cover.\n"
            f"CRITICAL: these topics are the SUBJECT MATTER of the post — they are not about this brand's own services or platform.\n"
            f"The brand voice/audience tells you HOW and WHO to write for — the topic tells you WHAT to write about.\n"
            f"{_topic_lines}\n"
            f"======================================================================="
        )
        content_focus_line = ""  # suppress pillars entirely — topics are set above
    else:
        topic_override_block = ""
        content_focus_line = f"Content pillars: {pillars_str}"

    prompt = f"""You are a senior social media strategist creating a 7-day content plan.

Your PRIMARY creative lens is this specific business: its products/services,
audience, goal, location, and the current season below. content_type / hook
style / format (assigned per day further down) are structural variety
requirements, not the source of the idea — never let "this is an Educational
post" be the whole thought. The idea must come from something real and
specific about THIS business, not a generic instance of its content_type.

{topic_override_block}

{brand_block}

{audience_block}

{voice_block}

{season_line}
{country_block}
{stage_block}
{user_date_block}

{performance_block}
{content_focus_line}
Platforms: {platforms_str}
Week starting: {week_start}
{extras_block}
{market_intel_block}
{avoid_repeat_block}
{force_token_block}
Generate a 7-day content plan. Every day must be a COMPLETE, ready-to-publish
content brief — not just a title. For each day produce:

- title: a short, punchy content idea title (max 10 words) — native to the platform and brand. If the title makes a countable claim ("3 things...", "5 mistakes...", "top 4..."), key_points below MUST deliver exactly that many.
- hook: the EXACT opening line a post using this idea would start with — real, usable text, not a description of a style (1 sentence).
- key_points: 2-5 concrete, specific points that make up the substance of the idea — things a person could copy straight into a caption or say on camera. Never vague ("share some tips") — always the actual point itself, spelled out.
- description: 2-3 sentences tying the idea together — what to say, who it speaks to, why it matters for this brand right now.
- caption_direction: 1-2 sentences of SPECIFIC guidance for writing this exact caption — must reference the actual hook/key_points/topic below it, never a generic content-type template.
- keywords: 2-4 real keywords or hashtag-worthy terms specific to THIS idea (not generic industry words like "business" or "tips").
- cta: ONE specific call-to-action sentence that fits this exact idea and drives the brand's stated goal — never a generic "Learn more" / "Shop now" unless it's genuinely the sharpest fit for this idea.
- video_idea: an alternative way to bring this SAME idea to life on video (always include one, every day):
  {{
    "format": one of "talking_head" | "product_demo" | "testimonial" | "tutorial" | "behind_the_scenes" | "trend_based" — pick whichever genuinely fits this idea best,
    "hook": exact opening line spoken/shown at the start of the video (can differ from the post hook if the video needs a different opener),
    "talking_points": 2-4 concrete things to say on camera, in order,
    "scenes": 2-4 concrete shots/scenes to film (e.g. "close-up of the product on a clean surface", "you talking to camera in your workspace"),
    "cta": the spoken/on-screen CTA for the video
  }}
- holiday_reference: null on every day UNLESS a real, relevant holiday/awareness day/cultural
  or industry date genuinely falls in this window per the country/date awareness note above —
  in that ONE case, set it to {{"name": "the real holiday/date name", "why_relevant": "1 sentence on why it fits this business"}}
  on the single day it applies to. Never fabricate one just to fill the field.

hook, key_points, caption_direction, keywords, and cta must all clearly
belong to the SAME idea — read them back together before finalizing and
confirm a reader could follow hook → key_points → caption_direction → cta
as one coherent thought. video_idea must be a genuinely usable video version
of that SAME core idea, not an unrelated concept bolted on.

Day assignments — follow the content type, hook style, AND format exactly for each day:
{days_block}

Return ONLY a valid JSON array of exactly 7 objects, each with ALL of the
fields below — no field may be omitted (holiday_reference may be null):
[
  {{
    "day_index": 0, "title": "...", "hook": "...", "key_points": ["...", "..."],
    "description": "...", "caption_direction": "...", "keywords": ["...", "..."], "cta": "...",
    "video_idea": {{"format": "talking_head", "hook": "...", "talking_points": ["...", "..."], "scenes": ["...", "..."], "cta": "..."}},
    "holiday_reference": null
  }},
  ...
  {{"day_index": 6, "title": "...", "hook": "...", "key_points": ["...", "..."], "description": "...", "caption_direction": "...", "keywords": ["...", "..."], "cta": "...", "video_idea": {{"format": "...", "hook": "...", "talking_points": ["...", "..."], "scenes": ["...", "..."], "cta": "..."}}, "holiday_reference": null}}
]

Rules:
- GROUND each idea in the trending topics and performance signals provided above — these are real signals, not generic suggestions
- EVERY day must use its assigned hook style and format — this is mandatory, not optional
- No two titles should start with the same word or phrase — maximum variety across all 7
- Never use list-post titles like "5 ways to..." or "5 mistakes..." more than ONCE across the 7 days
- No two days should share the same emotional tone — vary between inspiring, urgent, curious, empathetic, bold, playful, and authoritative
- Be SPECIFIC to this brand — use real product/service names, real audience pain points, real industry context
- Promotional: when a TOPIC is assigned, write about a deal/offer/value prop WITHIN that topic (e.g. if topic=finance, promote a financial tool or a deal for investors) — do NOT default to promoting this brand's own platform
- Educational: share an insight directly relevant to this brand's industry and audience
- Relatable: tap into a real emotion or experience the target audience would recognise instantly
- Engagement: pose a specific question or poll that this brand's followers would genuinely answer — vary the question style (poll, fill-in-the-blank, debate, personal story prompt)
- Behind the scenes: ROTATE each week between these distinct angles — workspace setup, product/service creation process, team doing actual work (NOT "Meet the team" introductions), packaging/delivery moment, before-and-after of a real project, client prep or discovery call, tool/workflow walkthrough. Do NOT default to team introduction posts.
- Match the brand voice exactly — if casual, be casual; if bold, be bold
- Never be generic — every idea should be impossible to copy-paste to a different brand
- If you notice you are writing similar angles back-to-back, STOP and pick a completely different direction
"""

    async def _call_and_parse(full_prompt: str, use_force: bool) -> List[Dict[str, Any]]:
        ai_request = AIService.build_ai_model(
            messages=[{"role": "user", "content": full_prompt}],
            model="gpt-4o",
            temperature=0.95 if use_force else 0.9,
        )
        response = await AIService.chat_completion(ai_request)
        if isinstance(response, dict) and response.get("error"):
            raise ValueError(response["error"])

        raw_text = response.choices[0].message.content.strip()
        # Strip markdown fences if present
        if raw_text.startswith("```"):
            raw_text = raw_text.split("```")[1]
            if raw_text.startswith("json"):
                raw_text = raw_text[4:]
        raw_text = raw_text.strip()

        parsed = json.loads(raw_text)
        if not isinstance(parsed, list) or len(parsed) != 7:
            raise ValueError(f"AI returned unexpected format: {raw_text[:200]}")
        return parsed

    print(f"[Calendar] _generate_ideas model=gpt-4o temperature={0.95 if force else 0.9} force={force}", flush=True)

    correction_block = ""
    ideas: List[Dict[str, Any]] = []
    for attempt in range(2):
        ideas = await _call_and_parse(prompt + correction_block, force)

        failures: Dict[int, List[str]] = {}
        for idea in ideas:
            issues = _validate_day(idea)
            if issues:
                failures[idea.get("day_index", -1)] = issues

        if not failures:
            break

        print(
            f"[Calendar] Validation failed for {len(failures)}/7 day(s) on attempt {attempt + 1}: {failures}",
            flush=True,
        )
        if attempt == 0:
            correction_lines = [f"Day {di}: {'; '.join(issues)}" for di, issues in sorted(failures.items())]
            correction_block = (
                "\n\n=== FIX THESE SPECIFIC PROBLEMS FROM YOUR PREVIOUS ATTEMPT ===\n"
                + "\n".join(correction_lines)
                + "\nRegenerate the FULL 7-day plan, keeping what already worked and fixing only what's listed above.\n"
                "==================================================================="
            )

    # Tie the stored format to the exact format each day was told to write for
    # (shuffled_formats[day_index]) rather than a disconnected analytics value —
    # otherwise copy that says "swipe through the carousel" can end up stored
    # under a day whose format field says "image".
    for idea in ideas:
        di = idea.get("day_index")
        if isinstance(di, int) and 0 <= di < len(shuffled_formats):
            idea["assigned_format"] = POST_FORMAT_TO_KEY.get(shuffled_formats[di], "image")

    return ideas


async def get_active_plan(
    user_id: str,
    db: AsyncIOMotorDatabase,
    week_start: Optional[str] = None,
    brand_id: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    if week_start is None:
        week_start = _get_monday(datetime.utcnow()).strftime("%Y-%m-%d")
    scope = _cal_scope(user_id, brand_id)
    doc = await db[COLLECTION].find_one(
        {**scope, "week_start": week_start, "status": "active"},
        {"_id": 0},
    )
    return doc


async def generate_plan(
    user_id: str,
    platforms: List[str],
    brand: Dict[str, Any],
    db: AsyncIOMotorDatabase,
    force: bool = False,
    brand_id: Optional[str] = None,
) -> Dict[str, Any]:
    now = datetime.utcnow()
    monday = _get_monday(now)
    week_start = monday.strftime("%Y-%m-%d")
    scope = _cal_scope(user_id, brand_id)

    previous_titles: List[str] = []
    previous_key_points: List[str] = []

    if force:
        # Grab current week's titles so AI doesn't regenerate the same ideas
        existing_active = await get_active_plan(user_id, db, week_start, brand_id=brand_id)
        if existing_active:
            previous_titles = [d.get("title", "") for d in existing_active.get("days", []) if d.get("title")]
        await db[COLLECTION].update_many(
            {**scope, "week_start": week_start, "status": "active"},
            {"$set": {"status": "archived"}},
        )
        # Bust all v2 trend cache entries for this industry so we get fresh keywords
        industry_temp = brand.get("industry", "")
        if industry_temp:
            try:
                await db["trends_cache"].delete_many(
                    {"_id": {"$regex": f"^v2:{re.escape(industry_temp.lower())}:"}}
                )
                print(f"[Calendar] Busted trend cache for '{industry_temp}' on force-regenerate")
            except Exception:
                pass
    else:
        existing = await get_active_plan(user_id, db, week_start, brand_id=brand_id)
        if existing:
            return existing

    industry = brand.get("industry", "")

    # Collect titles from last 4 weeks to prevent idea repetition
    for weeks_ago in range(1, 5):
        past_monday = (monday - timedelta(days=7 * weeks_ago)).strftime("%Y-%m-%d")
        past_plan = await db[COLLECTION].find_one(
            {**scope, "week_start": past_monday},
            {"_id": 0, "days": 1},
        )
        if past_plan:
            previous_titles += [d.get("title", "") for d in past_plan.get("days", []) if d.get("title")]
            for d in past_plan.get("days", []):
                previous_key_points += [str(p) for p in (d.get("key_points") or []) if p]

    # ── Data signals ──────────────────────────────────────────────────────────
    performance = await PerformanceAnalyticsService.get_user_performance(user_id, db)
    trend_keywords = await TrendDataService.get_trending_keywords(industry, db=db)

    # ── Enhanced PRD signals ──────────────────────────────────────────────────
    # Holidays & seasonal events (PRD Section 8)
    region = brand.get("region", "")
    upcoming_holidays = HolidayCalendarService.get_upcoming_holidays(week_start, region, industry)

    # Cultural moments & trending topics (PRD Section 7)
    trending_topics = CulturalMomentService.get_trending_topics(industry, region, week_start)
    cultural_moments = CulturalMomentService.get_cultural_moments(week_start, region)

    # Industry best practices (PRD Section 6)
    industry_best_practices = IndustryTrendService.get_industry_best_practices(industry)
    industry_trending = IndustryTrendService.get_trending_topics(industry)

    # ── Personalised content mix from performance data ────────────────────────
    week_number = monday.isocalendar()[1]
    if force:
        # On regenerate, pick a random variant + rotation so the type layout
        # genuinely changes (same week → same week_number, so we must randomise)
        variant_idx = secrets.randbelow(len(DEFAULT_MIX_VARIANTS))
        base = DEFAULT_MIX_VARIANTS[variant_idx][:]
        rotation = secrets.randbelow(6) + 1  # always rotate at least 1 slot
        mix = base[rotation:] + base[:rotation]
        print(f"[Calendar] Force-regen: variant={variant_idx} rotation={rotation} → mix={mix}")
    else:
        mix = _pick_mix_from_performance(performance, industry, brand, week_number=week_number)
        print(f"[Calendar] Week {week_number} → mix={mix}")

    generation_method = "ai"  # default fallback
    days: List[Dict[str, Any]] = []

    # ── AI generation (always used — grounded in trend + performance signals) ─
    _ai_error: Optional[str] = None
    try:
        if trend_keywords or performance.get("has_data"):
            generation_method = "data_driven" if performance.get("has_data") else "trend_driven"
        ai_ideas = await _generate_ideas(
            brand, mix, week_start, platforms,
            previous_titles=previous_titles,
            previous_key_points=previous_key_points,
            trend_keywords=trend_keywords or [],
            performance=performance,
            force=force,
        )
    except Exception as exc:
        import traceback as _tb
        _ai_error = str(exc)
        print(f"[Calendar] AI generation failed: {exc}\n{_tb.format_exc()}")
        ai_ideas = []

    for i, idea in enumerate(ai_ideas):
        day_date = (monday + timedelta(days=i)).strftime("%Y-%m-%d")
        day_of_week = (monday + timedelta(days=i)).strftime("%A")
        content_type = mix[i]
        title = idea.get("title", "")

        # Score against real signals for transparency
        kw = idea.get("keyword", "")
        trend_score = 0
        perf_score = 0
        if trend_keywords:
            match = next((t for t in trend_keywords if t["keyword"].lower() in title.lower()), None)
            if match:
                trend_score = match.get("trend_score", 0)
        if performance.get("has_data"):
            top_topics = performance.get("top_topics", [])
            title_lower = title.lower()
            if any(t.lower() in title_lower for t in top_topics):
                perf_score = 75

        # ── Enhanced PRD fields ───────────────────────────────────────────────
        # hook/key_points/caption_direction/keywords/cta/video_idea are now
        # generated by the SAME AI call as the title (see _generate_ideas) —
        # they're read straight off the idea rather than derived afterward,
        # since that's what makes them coherent with this specific idea.
        primary_goal = brand.get("primary_goal", "engagement")

        # Enhanced explanation with data backing (PRD Output requirement)
        enhanced_reason = ContentExplainerService.explain_recommendation(
            content_type=content_type,
            topic=title,
            post_day=day_of_week,
            primary_goal=primary_goal,
            historical_performance=performance if performance.get("has_data") else None,
            upcoming_holidays=upcoming_holidays,
            trending_topics=trending_topics + industry_trending,
            industry_best_practices=industry_best_practices,
        )

        # Deterministic (Nigeria/global) holidays for this date, plus whatever the AI
        # itself identified as relevant for the brand's own region this week (req 4) —
        # merged into the same list so the frontend's existing holiday badge just works
        # for every country, not only the ones HolidayCalendarService has hardcoded.
        day_holidays = [h for h in upcoming_holidays if h["date"] == day_date] if upcoming_holidays else []
        ai_holiday = idea.get("holiday_reference")
        if isinstance(ai_holiday, dict) and str(ai_holiday.get("name") or "").strip():
            ai_holiday_name = str(ai_holiday["name"]).strip()
            if not any(h.get("name", "").strip().lower() == ai_holiday_name.lower() for h in day_holidays):
                day_holidays.append({
                    "date": day_date,
                    "name": ai_holiday_name,
                    "type": "ai_suggested",
                    "relevance_score": 90,
                    "content_angle": str(ai_holiday.get("why_relevant") or "").strip(),
                })

        days.append({
            "day_index":           i,
            "date":                day_date,
            "day_of_week":         day_of_week,
            "content_type":        content_type,
            "title":               title,
            "description":         idea.get("description", ""),
            "keyword":             kw,
            "trend_score":         trend_score,
            "performance_score":   perf_score,
            "format_score":        0,
            "final_score":         round((trend_score * 0.4) + (perf_score * 0.4), 1),
            "reason":              enhanced_reason,
            "format":              idea.get("assigned_format") or (performance.get("top_formats") or ["image"])[0],
            "platforms":           platforms,
            # Coherent per-idea fields (all from the same AI call as title/description)
            "hook":                idea.get("hook", ""),
            "key_points":          idea.get("key_points", []),
            "caption_direction":   idea.get("caption_direction", ""),
            "keywords":            idea.get("keywords", []),
            "cta":                 idea.get("cta", ""),
            "video_idea":          idea.get("video_idea", {}),
            "upcoming_holidays":   day_holidays,
            "trending_topics":     trending_topics[:3] if trending_topics else [],
            "acted_on":            False,
            "acted_on_draft_ids":  [],
            "regenerated_count":   0,
            "last_regenerated_at": None,
        })

    # Guard: if both pipelines failed, restore the archived plan rather than
    # persisting an empty plan that would leave the user with a broken calendar.
    if not days:
        print(f"[Calendar] Both pipelines failed for user {user_id} — restoring previous plan")
        restored = await db[COLLECTION].find_one_and_update(
            {**scope, "week_start": week_start, "status": "archived"},
            {"$set": {"status": "active"}},
            sort=[("generated_at", -1)],
            return_document=True,
        )
        if restored:
            restored.pop("_id", None)
            return restored
        reason = f" Cause: {_ai_error}" if _ai_error else ""
        raise RuntimeError(f"Content generation failed and no previous plan to restore.{reason}")

    plan_id = str(uuid.uuid4())
    doc = {
        "plan_id":          plan_id,
        "user_id":          user_id,
        "brand_id":         brand_id,
        "week_start":       week_start,
        "generated_at":     now.isoformat(),
        "status":           "active",
        "generation_method":generation_method,
        "platforms":        platforms,
        "days":             days,
        "content_mix":      _compute_mix_ratios(mix),
        "data_signals": {
            "post_count":       performance.get("post_count", 0),
            "top_topics":       performance.get("top_topics", []),
            "top_formats":      performance.get("top_formats", []),
            "trend_source":     trend_keywords[0].get("source", "none") if trend_keywords else "none",
            "trend_kw_count":   len(trend_keywords),
        },
        "brand_snapshot": {
            "brand_name":          brand.get("brand_name"),
            "industry":            brand.get("industry"),
            "tagline":             brand.get("tagline"),
            "business_description":brand.get("business_description") or brand.get("product_description"),
            "key_products_services":brand.get("key_products_services") or [],
            "brand_voice":         brand.get("brand_voice") or brand.get("derived_voice"),
            "voice_sample":        brand.get("voice_sample"),
            "platform_tones":      brand.get("platform_tones") or {},
            "same_tone_everywhere":brand.get("same_tone_everywhere", True),
            "target_audience":     brand.get("target_audience"),
            "audience_age_range":  brand.get("audience_age_range"),
            "primary_goal":        brand.get("primary_goal"),
            "region":              brand.get("region"),
            "content_pillars":     brand.get("content_pillars") or [],
            "preferred_formats":   brand.get("preferred_formats") or [],
            "cta_styles":          brand.get("cta_styles") or [],
            "guardrails":          brand.get("guardrails") or {},
            "key_dates":           brand.get("key_dates"),
            "key_dates_structured":brand.get("key_dates_structured") or [],
            "posting_cadence":     brand.get("posting_cadence"),
            "website":             brand.get("website"),
        },
    }
    await db[COLLECTION].insert_one({**doc, "_id": plan_id})
    return doc


def _build_description(idea: Dict[str, Any], brand: Dict[str, Any]) -> str:
    """Build a brief description for a data-driven idea."""
    keyword  = idea.get("keyword", "")
    industry = brand.get("industry", "business")
    audience = brand.get("target_audience", "your audience")
    reason   = idea.get("reason", "")
    desc = (
        f"A {idea.get('content_type', 'content').replace('_', ' ')} post around "
        f'"{keyword}" — a trending topic in {industry} right now. '
        f"Speak directly to {audience}."
    )
    if reason:
        desc += f" Data signal: {reason}."
    return desc


async def regenerate_day(
    plan_id: str,
    day_index: int,
    user_id: str,
    db: AsyncIOMotorDatabase,
    brand_id: Optional[str] = None,
) -> Dict[str, Any]:
    scope = _cal_scope(user_id, brand_id)
    plan = await db[COLLECTION].find_one(
        {**scope, "plan_id": plan_id},
        {"_id": 0},
    )
    if not plan:
        raise ValueError("Plan not found")

    day = next((d for d in plan["days"] if d["day_index"] == day_index), None)
    if day is None:
        raise ValueError(f"Day {day_index} not found in plan")

    brand = plan.get("brand_snapshot") or {}
    mix = [d["content_type"] for d in sorted(plan["days"], key=lambda x: x["day_index"])]
    single_mix = [mix[day_index]]

    monday = datetime.strptime(plan["week_start"], "%Y-%m-%d")
    week_start = plan["week_start"]
    platforms = plan.get("platforms") or []

    # Build a targeted prompt for just one day
    content_type = mix[day_index]
    brand_name = brand.get("brand_name") or "the brand"
    industry = brand.get("industry") or "business"
    voice = brand.get("brand_voice") or "professional and engaging"
    audience = brand.get("target_audience") or "general audience"
    platforms_str = ", ".join(platforms) if platforms else "social media"
    day_name = WEEK_DAYS[day_index]
    tagline = brand.get("tagline", "")
    description = brand.get("business_description") or brand.get("product_description", "")
    products = brand.get("key_products_services") or []
    products_str = ", ".join(products) if products else ""
    pillars = brand.get("content_pillars") or []
    pillars_str = ", ".join(pillars) if pillars else ""
    voice_sample = brand.get("voice_sample", "")
    region = brand.get("region", "")
    guardrails = brand.get("guardrails") or {}
    avoid = guardrails.get("avoid_topics") or guardrails.get("avoid") or []
    avoid_str = ", ".join(avoid) if avoid else ""

    # Avoid all existing day titles in this plan
    existing_titles = [d.get("title", "") for d in plan["days"] if d.get("title") and d["day_index"] != day_index]

    brand_line = f"{brand_name}"
    if tagline:
        brand_line += f' ("{tagline}")'
    if industry:
        brand_line += f" — {industry}"
    if description:
        brand_line += f"\nWhat they do: {description}"
    if products_str:
        brand_line += f"\nProducts/services: {products_str}"

    avoid_block = ""
    if existing_titles:
        avoid_block += "\nAlready used this week (do not repeat):\n" + "\n".join(f"- {t}" for t in existing_titles)
    if avoid_str:
        avoid_block += f"\nTopics to avoid: {avoid_str}"

    country_block = ""
    if region:
        country_block = (
            f"Country/date awareness: this brand's audience is in {region}. If a real, "
            f"well-known public holiday, awareness day, or industry date genuinely falls "
            f"near {day_name} for {region} and is relevant to this business, let it shape "
            f"the idea AND set holiday_reference below — never invent a date you're not "
            f"confident actually exists; leave holiday_reference null otherwise."
        )

    stage_block = (
        "Business stage: infer this brand's apparent stage of growth from the details "
        "above and let it inform tone where relevant (e.g. an early-stage brand benefits "
        "more from trust-building/story content, an established one can lean harder into "
        "authority/scale content)."
    )

    # Same deterministic check as _generate_ideas — if the business owner saved a
    # date that lands on THIS exact day, it's non-negotiable, not left to AI recall.
    user_date_block = ""
    day_date_str = day.get("date") or ""
    for kd in (brand.get("key_dates_structured") or []):
        label = str((kd or {}).get("label") or "").strip()
        date_str = str((kd or {}).get("date") or "").strip()
        if label and date_str and date_str == day_date_str:
            user_date_block = (
                f"MANDATORY: the business owner personally saved {day_date_str} as \"{label}\" "
                f"in their Brand Playbook — this day's idea MUST be built around it (not a general "
                f"public holiday, non-negotiable). Set holiday_reference to "
                f'{{"name": "{label}", "why_relevant": "..."}}.'
            )
            break

    base_prompt = f"""You are a senior social media strategist.

{brand_line}
Brand voice: {voice}{f' | Example: "{voice_sample[:150]}"' if voice_sample else ''}
Target audience: {audience}{f' | {region} market' if region else ''}
{f'Content pillars: {pillars_str}' if pillars_str else ''}
Platforms: {platforms_str}
{country_block}
{stage_block}
{user_date_block}
{avoid_block}

Generate ONE new, COMPLETE {CONTENT_TYPE_LABELS[content_type]} content brief for {day_name}
— a full, ready-to-publish idea, not just a title.
Make it different from the previous idea: "{day.get('title', '')}"
Be specific to this brand — use real product names, audience pain points, industry context.
Your creative lens is this specific business — its products, audience, goal, and location —
not a generic instance of "{CONTENT_TYPE_LABELS[content_type]}".

Return ONLY a valid JSON object with ALL of these fields:
{{
  "title": "max 10 words. If it makes a countable claim (e.g. '3 things'), key_points must deliver that many.",
  "hook": "the exact opening line this post would start with — real usable text, 1 sentence",
  "key_points": ["2-5 concrete, specific points a person could copy straight into the caption"],
  "description": "2-3 sentences tying the idea together — what to say, who it speaks to, why it matters now",
  "caption_direction": "1-2 sentences of specific guidance for writing this exact caption",
  "keywords": ["2-4 real keywords/hashtag-worthy terms specific to this idea"],
  "cta": "one specific call-to-action sentence that fits this exact idea",
  "video_idea": {{
    "format": "one of talking_head | product_demo | testimonial | tutorial | behind_the_scenes | trend_based",
    "hook": "exact opening line for the video",
    "talking_points": ["2-4 concrete things to say on camera, in order"],
    "scenes": ["2-4 concrete shots/scenes to film"],
    "cta": "the spoken/on-screen CTA for the video"
  }},
  "holiday_reference": null or {{"name": "the real holiday/date name", "why_relevant": "1 sentence on why it fits this business"}}
}}

hook, key_points, caption_direction, keywords, and cta must all clearly belong to the
SAME idea — they must cohere as one thought, not read like separate templates stitched together.
"""

    async def _call_and_parse(full_prompt: str) -> Dict[str, Any]:
        ai_request = AIService.build_ai_model(
            messages=[{"role": "user", "content": full_prompt}],
            temperature=0.9,
        )
        response = await AIService.chat_completion(ai_request)
        if isinstance(response, dict) and response.get("error"):
            raise ValueError(response["error"])

        raw_text = response.choices[0].message.content.strip()
        if raw_text.startswith("```"):
            raw_text = raw_text.split("```")[1]
            if raw_text.startswith("json"):
                raw_text = raw_text[4:]
        return json.loads(raw_text.strip())

    correction_block = ""
    new_idea: Dict[str, Any] = {}
    for attempt in range(2):
        new_idea = await _call_and_parse(base_prompt + correction_block)
        issues = _validate_day(new_idea)
        if not issues:
            break
        print(f"[Calendar] regenerate_day validation failed on attempt {attempt + 1}: {issues}", flush=True)
        if attempt == 0:
            correction_block = (
                "\n\n=== FIX THESE SPECIFIC PROBLEMS FROM YOUR PREVIOUS ATTEMPT ===\n"
                + "; ".join(issues)
                + "\n==================================================================="
            )

    # Deterministic holidays for this specific date, merged with whatever the AI itself
    # identified as relevant for the brand's region this time (req 4) — same merge
    # pattern as generate_plan, so a regenerated day still gets full holiday coverage.
    day_date = day.get("date") or (monday + timedelta(days=day_index)).strftime("%Y-%m-%d")
    day_holidays = [
        h for h in HolidayCalendarService.get_upcoming_holidays(week_start, region, industry)
        if h["date"] == day_date
    ]
    ai_holiday = new_idea.get("holiday_reference")
    if isinstance(ai_holiday, dict) and str(ai_holiday.get("name") or "").strip():
        ai_holiday_name = str(ai_holiday["name"]).strip()
        if not any(h.get("name", "").strip().lower() == ai_holiday_name.lower() for h in day_holidays):
            day_holidays.append({
                "date": day_date,
                "name": ai_holiday_name,
                "type": "ai_suggested",
                "relevance_score": 90,
                "content_angle": str(ai_holiday.get("why_relevant") or "").strip(),
            })

    now = datetime.utcnow()
    await db[COLLECTION].update_one(
        {**scope, "plan_id": plan_id},
        {
            "$set": {
                f"days.{day_index}.title": new_idea.get("title", ""),
                f"days.{day_index}.description": new_idea.get("description", ""),
                f"days.{day_index}.hook": new_idea.get("hook", ""),
                f"days.{day_index}.key_points": new_idea.get("key_points", []),
                f"days.{day_index}.caption_direction": new_idea.get("caption_direction", ""),
                f"days.{day_index}.keywords": new_idea.get("keywords", []),
                f"days.{day_index}.cta": new_idea.get("cta", ""),
                f"days.{day_index}.video_idea": new_idea.get("video_idea", {}),
                f"days.{day_index}.upcoming_holidays": day_holidays,
                f"days.{day_index}.regenerated_count": day.get("regenerated_count", 0) + 1,
                f"days.{day_index}.last_regenerated_at": now.isoformat(),
            }
        },
    )

    updated = await db[COLLECTION].find_one({**scope, "plan_id": plan_id}, {"_id": 0})
    return updated


async def mark_acted_on(
    plan_id: str,
    day_index: int,
    draft_ids: List[str],
    user_id: str,
    db: AsyncIOMotorDatabase,
    brand_id: Optional[str] = None,
) -> None:
    scope = _cal_scope(user_id, brand_id)
    await db[COLLECTION].update_one(
        {**scope, "plan_id": plan_id},
        {
            "$set": {f"days.{day_index}.acted_on": True},
            "$push": {f"days.{day_index}.acted_on_draft_ids": {"$each": draft_ids}},
        },
    )


async def get_today_suggestion(
    user_id: str,
    db: AsyncIOMotorDatabase,
    brand_id: Optional[str] = None,
) -> Dict[str, Any]:
    now = datetime.utcnow()
    week_start = _get_monday(now).strftime("%Y-%m-%d")
    plan = await get_active_plan(user_id, db, week_start, brand_id=brand_id)
    if not plan:
        return {"has_plan": False}

    today_str = now.strftime("%Y-%m-%d")
    today_day = next((d for d in plan["days"] if d["date"] == today_str), None)
    if today_day is None:
        return {"has_plan": True, "plan_id": plan["plan_id"], "today": None}

    return {
        "has_plan": True,
        "plan_id": plan["plan_id"],
        "day_index": today_day["day_index"],
        "today": today_day,
    }
