"""
Layer Extraction Service - GPT-4 Vision Analysis

Analyzes AI-generated images to extract editable layers:
- Text content, position, font characteristics
- Logo position and size
- Object/product positions
- Layout structure

This enables Canvas Editor functionality on images generated by the AI.
"""

from typing import Dict, Any, List, Optional
import json
from app.services.AIService import client as openai_client


class LayerExtractionService:
    """Service for extracting editable layers from baked images using GPT-4 Vision"""

    @staticmethod
    async def extract_layers(
        image_url: str,
        prompt_metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Analyze AI-generated image and extract editable layers

        Args:
            image_url: URL of the generated image to analyze
            prompt_metadata: Optional context about what was in the generation prompt
                           (helps GPT-4 Vision make better inferences)

        Returns:
            {
                "text_layers": [...],
                "logo": {...},
                "objects": [...],
                "background_description": "..."
            }
        """
        # Build analysis prompt
        analysis_prompt = LayerExtractionService._build_analysis_prompt(prompt_metadata)

        try:
            response = await openai_client.chat.completions.create(
                model="gpt-4o",
                messages=[{
                    "role": "user",
                    "content": [
                        {"type": "text", "text": analysis_prompt},
                        {"type": "image_url", "image_url": {"url": image_url}}
                    ]
                }],
                response_format={"type": "json_object"},
                max_tokens=2000,
                temperature=0.1  # Low temperature for consistent analysis
            )

            # Parse response
            result = json.loads(response.choices[0].message.content)

            print(f"[LayerExtraction] Extracted {len(result.get('text_layers', []))} text layers")
            print(f"[LayerExtraction] Logo detected: {result.get('logo') is not None}")

            return result

        except Exception as e:
            print(f"[LayerExtraction] ❌ Error: {e}")
            return {
                "text_layers": [],
                "logo": None,
                "objects": [],
                "background_description": "",
                "error": str(e)
            }

    @staticmethod
    def _build_analysis_prompt(metadata: Optional[Dict[str, Any]]) -> str:
        """Build GPT-4 Vision analysis prompt"""

        base_prompt = """Analyze this social media post image and extract all editable elements as precise JSON.

**Your task:**
1. Identify ALL text elements (headlines, subtext, CTAs, price tags, etc.)
2. Estimate their exact positions, sizes, and visual properties
3. Detect logo position and size
4. Identify any product/object placements
5. Describe the background style

**Return strict JSON with this structure:**
```json
{
  "text_layers": [
    {
      "content": "The actual text you see",
      "role": "headline" | "subtext" | "cta" | "price" | "badge",
      "x": 100,
      "y": 200,
      "width": 500,
      "height": 80,
      "fontSize": 72,
      "fontWeight": 400 | 700,
      "color": "#FFFFFF",
      "fontFamily": "estimated font name or 'sans-serif'",
      "textAlign": "left" | "center" | "right",
      "confidence": 0.95
    }
  ],
  "logo": {
    "x": 880,
    "y": 950,
    "width": 120,
    "height": 60,
    "position": "bottom-right",
    "confidence": 0.9
  },
  "objects": [
    {
      "type": "product" | "decoration" | "shape",
      "description": "lipstick product",
      "x": 400,
      "y": 300,
      "width": 300,
      "height": 500,
      "confidence": 0.85
    }
  ],
  "background_description": "Purple gradient with bokeh light effects",
  "canvas_width": 1080,
  "canvas_height": 1080
}
```

**Critical requirements:**
- ALL text must be extracted character-for-character (no paraphrasing)
- Position (x,y) is top-left corner of text/element
- Font size should be estimated in pixels (typical range: 24-96px)
- Color should be hex format (#RRGGBB)
- Confidence: your certainty (0.0 - 1.0)

**Be precise:** The Canvas Editor will use these values to recreate editable layers."""

        # Add metadata context if available
        if metadata:
            context_lines = ["\n**Known generation context:**"]

            if "headline" in metadata:
                context_lines.append(f"- Expected headline text: \"{metadata['headline']}\"")

            if "subtext" in metadata:
                context_lines.append(f"- Expected subtext: \"{metadata['subtext']}\"")

            if "brand_name" in metadata:
                context_lines.append(f"- Brand name: {metadata['brand_name']}")

            if "logo_position" in metadata:
                context_lines.append(f"- Logo should be: {metadata['logo_position']}")

            if "visual_style" in metadata:
                context_lines.append(f"- Visual style: {metadata['visual_style']}")

            context_lines.append("\nUse this context to improve accuracy, but analyze what you actually SEE in the image.")

            base_prompt += "\n".join(context_lines)

        return base_prompt

    @staticmethod
    def convert_to_document_layers(
        extraction_result: Dict[str, Any],
        background_url: str
    ) -> List[Dict[str, Any]]:
        """
        Convert GPT-4 Vision extraction result to layered document format

        Args:
            extraction_result: Result from extract_layers()
            background_url: URL of the original generated image

        Returns:
            List of layer objects ready for LayeredDocumentService
        """
        layers = []

        # Add background layer (z_index: 0)
        layers.append({
            "id": "layer_bg",
            "type": "ai_generated_background",
            "z_index": 0,
            "url": background_url,
            "locked": True,
            "visible": True,
            "extraction_metadata": {
                "description": extraction_result.get("background_description", "")
            }
        })

        # Add text layers (z_index: 10+)
        text_layers = extraction_result.get("text_layers", [])
        for i, text_layer in enumerate(text_layers):
            layers.append({
                "id": f"layer_text_{i}",
                "type": "text",
                "z_index": 10 + i,
                "content": text_layer.get("content", ""),
                "font_family": text_layer.get("fontFamily", "Arial"),
                "font_size": text_layer.get("fontSize", 48),
                "font_weight": text_layer.get("fontWeight", 400),
                "color": text_layer.get("color", "#FFFFFF"),
                "x": text_layer.get("x", 100),
                "y": text_layer.get("y", 100),
                "max_width": text_layer.get("width"),
                "text_align": text_layer.get("textAlign", "left"),
                "line_height": 1.2,
                "letter_spacing": 0,
                "locked": False,
                "visible": True,
                "extraction_metadata": {
                    "role": text_layer.get("role", "text"),
                    "confidence": text_layer.get("confidence", 0.0)
                }
            })

        # Add logo layer (z_index: 20)
        logo = extraction_result.get("logo")
        if logo:
            layers.append({
                "id": "layer_logo",
                "type": "brand_asset",
                "asset_role": "logo",
                "z_index": 20,
                "url": "",  # Will be populated from brand profile
                "x": logo.get("x", 880),
                "y": logo.get("y", 950),
                "width": logo.get("width", 120),
                "height": logo.get("height", 60),
                "opacity": 1.0,
                "locked": False,
                "visible": True,
                "extraction_metadata": {
                    "position": logo.get("position", "bottom-right"),
                    "confidence": logo.get("confidence", 0.0)
                }
            })

        # Add object layers (z_index: 5+)
        objects = extraction_result.get("objects", [])
        for i, obj in enumerate(objects):
            layers.append({
                "id": f"layer_object_{i}",
                "type": "extracted_object",
                "z_index": 5 + i,
                "x": obj.get("x", 0),
                "y": obj.get("y", 0),
                "width": obj.get("width", 100),
                "height": obj.get("height", 100),
                "locked": True,  # Extracted objects locked by default
                "visible": True,
                "extraction_metadata": {
                    "object_type": obj.get("type", "object"),
                    "description": obj.get("description", ""),
                    "confidence": obj.get("confidence", 0.0)
                }
            })

        return layers

    @staticmethod
    async def extract_and_create_document(
        image_url: str,
        prompt_metadata: Optional[Dict[str, Any]] = None,
        canvas_width: int = 1080,
        canvas_height: int = 1080
    ) -> Dict[str, Any]:
        """
        Complete workflow: Extract layers and create layered document

        This is a convenience method that combines:
        1. GPT-4 Vision extraction
        2. Layer conversion
        3. Document creation

        Args:
            image_url: URL of generated image
            prompt_metadata: Generation context
            canvas_width, canvas_height: Canvas dimensions

        Returns:
            Complete layered document ready to save
        """
        from .layered_document_service import LayeredDocumentService

        # Extract layers from image
        extraction_result = await LayerExtractionService.extract_layers(
            image_url,
            prompt_metadata
        )

        # Create base document
        document = LayeredDocumentService.create_document(
            canvas_width=canvas_width,
            canvas_height=canvas_height,
            aspect_ratio="1:1"
        )

        # Convert extraction to layers
        layers = LayerExtractionService.convert_to_document_layers(
            extraction_result,
            image_url
        )

        # Add layers to document
        document["layers"] = layers

        # Add extraction metadata
        document["metadata"]["extraction_method"] = "gpt4_vision"
        document["metadata"]["extraction_confidence"] = extraction_result.get("confidence", 0.0)

        return document
