"""
True product compositing — pixel-exact product placement for AI-generated scenes.

The reference-image edit pipeline in image_content_service.py asks GPT-Image-2 to
redraw the ENTIRE frame, including the product, from a text description. No matter
how detailed that description gets, the product is being reconstructed, not
preserved — confirmed live, repeatedly: label text and glass colour drifting from
the real photo regardless of how the forensic-analysis prompt was tuned.

This module takes the opposite approach for the product itself: the background/scene
is generated by AI (no product in the prompt at all), and the real, unmodified
product cutout — the actual uploaded photo's pixels, background already removed via
app/utils/background_removal.py — is pasted onto it with ordinary PIL compositing,
the same technique already used successfully for logo overlay in
ImageContentService._overlay_logo. The product region is then literally the same
pixels as the upload; there is nothing left for the AI to get wrong.

Placement math mirrors the English composition-mode descriptions already used to
prompt the AI in image_content_service.py's immersive/editorial blocks, so a
composited image's framing reads the same as today's AI-drawn framing rather than a
naive centred paste.
"""

import io
from typing import Tuple

from PIL import Image, ImageDraw, ImageFilter


def compute_product_placement(canvas_w: int, canvas_h: int, composition_mode: str) -> Tuple[int, int, int, int]:
    """Returns (x, y, w, h) — the rectangle the product should be fit into,
    preserving its own aspect ratio within that rectangle.

    "immersive" (default) mirrors the prompt's own language: product is the
    "gravitational centre... slightly off-centre (40/60 split)", with
    "ABOVE: atmospheric space where text lives" — i.e. text sits above, so the
    product sits in the lower-centre of the frame, off-centre horizontally
    rather than dead-centre. Sized to ~62% of canvas height (large enough to be
    "the sharpest element", not so large it fills the frame and leaves no room
    for the atmosphere/text the rest of the prompt still asks the background
    generation for).

    "editorial" mirrors "PRODUCT ZONE (55% of frame, positioned left or right)"
    — defaults to the right zone (matches the majority of this session's own
    test generations, which put the product right-of-centre with text at
    left), sized to fit within that 55% zone with margin.
    """
    if composition_mode == "editorial":
        zone_w = int(canvas_w * 0.55)
        zone_x = canvas_w - zone_w  # right-hand zone
        margin = int(zone_w * 0.12)
        w = zone_w - margin * 2
        h = int(canvas_h * 0.72)
        x = zone_x + margin
        y = (canvas_h - h) // 2
        return (x, y, w, h)

    # immersive (default)
    h = int(canvas_h * 0.62)
    w = int(canvas_w * 0.42)
    # Horizontally off-centre — anchored right-of-centre (~58% across), leaving
    # the left/upper-left "atmospheric" zone clearer for headline text, matching
    # this session's own reference generations.
    x = int(canvas_w * 0.58) - w // 2
    x = max(0, min(x, canvas_w - w))
    # Vertically anchored toward the lower-middle — leaves the "ABOVE" zone
    # (per the immersive prompt) clear at the top for text/atmosphere.
    y = int(canvas_h * 0.60) - h // 2
    y = max(0, min(y, canvas_h - h))
    return (x, y, w, h)


def _fit_within(img: Image.Image, box_w: int, box_h: int) -> Image.Image:
    """Resize img (preserving aspect ratio) to fit entirely within box_w x box_h."""
    src_w, src_h = img.size
    scale = min(box_w / src_w, box_h / src_h)
    new_w = max(1, int(src_w * scale))
    new_h = max(1, int(src_h * scale))
    return img.resize((new_w, new_h), Image.LANCZOS)


def _draw_soft_shadow(canvas: Image.Image, box: Tuple[int, int, int, int]) -> None:
    """Draws a soft blurred dark ellipse under the product's placement box, for
    basic visual grounding. Deliberately simple — not lighting/perspective-aware
    (see plan's "Explicitly deferred" section) — a cheap, easy-to-disable step,
    not required for correctness. Mutates `canvas` in place."""
    x, y, w, h = box
    shadow_layer = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(shadow_layer)
    ellipse_w = int(w * 0.8)
    ellipse_h = max(8, int(h * 0.06))
    ellipse_x = x + (w - ellipse_w) // 2
    ellipse_y = y + h - ellipse_h // 2
    draw.ellipse(
        [ellipse_x, ellipse_y, ellipse_x + ellipse_w, ellipse_y + ellipse_h],
        fill=(0, 0, 0, 90),
    )
    shadow_layer = shadow_layer.filter(ImageFilter.GaussianBlur(radius=max(4, ellipse_h // 2)))
    canvas.alpha_composite(shadow_layer)


def composite_product_onto_background(
    background_bytes: bytes,
    cutout_bytes: bytes,
    placement: Tuple[int, int, int, int],
    add_shadow: bool = True,
) -> bytes:
    """Pastes the real product cutout onto the AI-generated background at
    `placement`, preserving the cutout's own aspect ratio and using its own
    alpha channel as the paste mask — same pattern as
    ImageContentService._overlay_logo. Returns PNG bytes (RGBA preserved, since
    further compositing — logo overlay, text — may still follow)."""
    background = Image.open(io.BytesIO(background_bytes)).convert("RGBA")
    cutout = Image.open(io.BytesIO(cutout_bytes)).convert("RGBA")

    x, y, box_w, box_h = placement
    fitted = _fit_within(cutout, box_w, box_h)
    fw, fh = fitted.size
    # Centre the fitted product within its placement box (it may not exactly
    # fill box_w x box_h once aspect ratio is preserved).
    paste_x = x + (box_w - fw) // 2
    paste_y = y + (box_h - fh) // 2

    if add_shadow:
        _draw_soft_shadow(background, (paste_x, paste_y, fw, fh))

    background.paste(fitted, (paste_x, paste_y), fitted)

    out_buf = io.BytesIO()
    background.save(out_buf, format="PNG")
    return out_buf.getvalue()
