"""
Day 1 → Day 30 — VSG-01 v3 §2.9 (SEED-078).

"The change is physical and verifiable. Excluded outright for health,
weight, skin and appearance." Two panels, identical crop/framing/lighting
(caller responsibility — this module can't verify photographic similarity
between two source images), minimal `ink-quiet` labels. No arrows, no glow,
no enhancement.

**Both images must be the user's own real work. Never generate a synthetic
transformation** — a fabricated before-and-after is a misleading claim and
an undeclared-AI problem simultaneously. This module never has a code path
that could produce a second image from the first; it only ever places two
URLs the caller supplies.

Hard checks (§2.9) — the strictest exclusion in the library, stronger than
Review Card's "no timed claims within a category" (§2.1/SEED-078, the same
corpus record this format's own id points back to): here the *category*
itself is excluded outright, not just certain phrasing within it. "Side-by-
side imagery is flagged by multimodal review as an implied transformation,
and a timeframe paired with it is treated as a misleading transformation
claim even without an explicit guarantee" — meaning even a real, honestly-
labelled pair of photos reads as a transformation claim by construction.
That's fine for a repair, an installation, a fitted-out room, a training
cohort; it's never fine for a body.

Enforced two ways, not one, given "excluded outright" is stronger language
than Review Card's "no timed claims":

1. `category` is a closed allowlist (`_PERMITTED_CATEGORIES`, mirroring
   §2.9's own "Permitted:" list exactly) rather than a health/appearance
   *blocklist* — a blocklist only catches wording it recognises; an
   allowlist can't be used for anything the spec didn't name.
   `DisallowedCategory` otherwise.

2. Defense-in-depth: the labels are also scanned for health/appearance
   vocabulary (`_content_guards.mentions_health_or_appearance_outcome`,
   shared with Review Card's guard) in case a caller picks a permitted
   category but slips a body-related caption in anyway — e.g.
   category="repair_or_restoration" with day1_label="Before treatment".
"""
from typing import Dict, Tuple

from ._content_guards import mentions_health_or_appearance_outcome
from .tokens import AdFormatDef, PLACEHOLDER_TOKENS
from app.agents.social_media_manager.services.document_renderer_service import DocumentRendererService

FORMAT = AdFormatDef(
    format_id="SEED-078",
    name="Day 1 → Day 30",
    asset_source="upload",  # CreativeSource.UPLOAD ("upload_as_is") x2 — both panels
    layers_used="L4",
    # Requirement.PRODUCT_PHOTO is a best-fit reuse, not a precise semantic
    # match — "product" undersells a repair, a built room or a training
    # cohort — but the underlying gate is the same one PRODUCT_PHOTO exists
    # for: never surface a format whose asset_source is upload_as_is for a
    # business with no real photo to build it from. A more precisely named
    # requirement can replace this later without changing behaviour.
    requires=["product_photo"],
)

_FONT_LABEL = 44  # §1.6 floor — applies even to "minimal" labels


class DisallowedCategory(ValueError):
    """§2.9: excluded outright for health, weight, skin and appearance —
    permitted only for installation/construction progress, a space
    before-and-after fitting, a repair or restoration, or a training
    cohort. See module docstring for why this is a closed allowlist."""
    pass


_PERMITTED_CATEGORIES = {
    "installation_or_construction_progress",
    "space_before_after_fitting",
    "repair_or_restoration",
    "training_cohort",
}


def build_document(
    day1_image_url: str,
    day30_image_url: str,
    category: str,
    day1_label: str = "Day 1",
    day30_label: str = "Day 30",
    canvas_size: Tuple[int, int] = (1080, 1080),
    tokens: Dict[str, str] = None,
) -> Dict:
    """
    day1_image_url / day30_image_url: two real, caller-supplied photographs
    — never generated by this module or anything upstream of it (§1.2).
    category: must be one of `_PERMITTED_CATEGORIES` — raises
    `DisallowedCategory` otherwise, including for any health/weight/skin/
    appearance framing regardless of how the images were actually taken.
    day1_label / day30_label: minimal captions only (§2.9: "minimal labels
    in ink-quiet") — also scanned for health/appearance vocabulary.
    """
    if category not in _PERMITTED_CATEGORIES:
        raise DisallowedCategory(
            f"category {category!r} is not permitted — §2.9 allows only "
            f"{sorted(_PERMITTED_CATEGORIES)}, and excludes health/weight/"
            "skin/appearance outright regardless of category wording"
        )
    for label in (day1_label, day30_label):
        if mentions_health_or_appearance_outcome(label):
            raise DisallowedCategory(
                f"label {label!r} reads as a health/appearance outcome — "
                "not permitted even under an otherwise-allowed category (§2.9)"
            )

    t = tokens or PLACEHOLDER_TOKENS
    width, height = canvas_size
    layers = []
    z = 0

    label_zone_height = 96
    panel_height = height - label_zone_height
    gap = 6
    panel_width = (width - gap) // 2

    for image_url, panel_x in ((day1_image_url, 0), (day30_image_url, panel_width + gap)):
        z += 1
        layers.append({
            "type": "composited_product", "z_index": z,
            "url": image_url,
            "x": panel_x, "y": 0, "width": panel_width, "height": panel_height,
        })

    # A plain neutral seam between the two panels — structural separation,
    # not the kind of "enhancement" §2.9 prohibits (that rule targets
    # arrows/glow/colour-grading that dramatise the transformation itself;
    # a divider line carries no directional or evaluative meaning, same
    # category as Us vs Them's row dividers).
    z += 1
    layers.append({
        "type": "shape", "z_index": z, "shape": "line",
        "x1": panel_width + gap // 2, "y1": 0,
        "x2": panel_width + gap // 2, "y2": panel_height,
        "color": t["edge"], "stroke_width": 2,
    })

    label_y = panel_height + 24
    for label, panel_x in ((day1_label, 0), (day30_label, panel_width + gap)):
        z += 1
        layers.append({
            "type": "text", "z_index": z, "content": label,
            "x": panel_x + panel_width // 2, "y": label_y,
            "font_size": _FONT_LABEL, "color": t["ink-quiet"],
            "text_align": "ma",  # horizontally centred under its own panel
        })

    return {
        "canvas": {"width": width, "height": height, "background_color": t["surface"]},
        "layers": layers,
    }


async def render(*args, **kwargs) -> bytes:
    document = build_document(*args, **kwargs)
    return await DocumentRendererService.render_to_png(document)
